In [2]:
import sqlite3
import pandas as pd
from pathlib import Path
csv_path = Path("/Users/keerthanavenkatesan/Documents/Data Managment/CS210FinalProject/Spotify_Popularity_Prediction/data/raw/spotify_100k.csv")
df = pd.read_csv(csv_path)

print(df.shape)
df.head()

(100000, 20)

,Unnamed: 0,artist_name,track_name,track_id,popularity,year,genre,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
0,1054304,Cabas,Amor De Mis Amores,3FTqjWmL21xi4HTTOq94EQ,38,2006,alt-rock,0.725,0.553,6,-6.319,0,0.0340,0.276000,0.000007,0.1850,0.729,90.009,206653,4
1,621408,Ketil Bjørnstad,Første sang,0Pt7ESPgrdTdaxp2f29hX2,11,2023,swedish,0.277,0.164,9,-16.743,0,0.0373,0.878000,0.000181,0.3350,0.184,89.308,459733,4
2,1121669,Project 86,Evil (A Chorus Of Resistance),75Ub3ckaoTdzgH9Azeu8cY,38,2007,alt-rock,0.486,0.927,2,-4.845,0,0.0428,0.000003,0.014500,0.0952,0.377,135.540,183373,4
3,439351,Ital Tek,Open Heart,5WEPna9GWi0NkqVLAkEKNN,18,2020,dubstep,0.411,0.442,1,-12.745,0,0.0270,0.485000,0.926000,0.1910,0.172,174.019,347610,3
4,266036,I-Roy,Irie Right,6peHySxvmZaRF9YEwUsggq,18,2017,dancehall,0.748,0.660,10,-4.648,0,0.2710,0.125000,0.000000,0.0783,0.400,75.583,196179,4

In [4]:
db_path = Path("/Users/keerthanavenkatesan/Documents/Data Managment/CS210FinalProject/Spotify_Popularity_Prediction/data/spotify.db")

conn = sqlite3.connect(db_path)
df.to_sql("tracks", conn, if_exists="replace", index=False)

print("Fresh database created and table 'tracks' loaded.")

Fresh database created and table 'tracks' loaded.

In [5]:
create_stmt = pd.read_sql("""
    SELECT sql 
    FROM sqlite_master 
    WHERE type='table' AND name='tracks';
""", conn)

print(create_stmt.sql[0])

CREATE TABLE "tracks" (
"Unnamed: 0" INTEGER,
  "artist_name" TEXT,
  "track_name" TEXT,
  "track_id" TEXT,
  "popularity" INTEGER,
  "year" INTEGER,
  "genre" TEXT,
  "danceability" REAL,
  "energy" REAL,
  "key" INTEGER,
  "loudness" REAL,
  "mode" INTEGER,
  "speechiness" REAL,
  "acousticness" REAL,
  "instrumentalness" REAL,
  "liveness" REAL,
  "valence" REAL,
  "tempo" REAL,
  "duration_ms" INTEGER,
  "time_signature" INTEGER
)

In [5]:
pd.read_sql("SELECT COUNT(*) FROM tracks", conn)

   COUNT(*)
0    100000

In [7]:
query_genres = """
SELECT genre, COUNT(*) AS count, AVG(popularity) AS avg_popularity
FROM tracks
GROUP BY genre
ORDER BY count DESC
LIMIT 20;
"""
pd.read_sql(query_genres, conn)

          genre  count  avg_popularity
0        gospel   1942       18.961895
1       ambient   1869       20.499732
2           emo   1831       23.788640
3        indian   1797        8.904285
4   black-metal   1796       11.046214
5      alt-rock   1793       38.832683
6         k-pop   1769       27.381006
7      acoustic   1768       17.898756
8         blues   1712       21.961449
9     dancehall   1665       14.653453
10        forro   1663       11.805171
11      new-age   1649       11.590055
12          dub   1647       16.513661
13      spanish   1645       23.525228
14       comedy   1641       10.057282
15        chill   1639       26.496644
16        samba   1605        9.780685
17       french   1599       25.949343
18      country   1564       32.971228
19    classical   1557       25.073218

In [8]:
query_years = """
SELECT year, COUNT(*) AS count, AVG(popularity) AS avg_popularity
FROM tracks
GROUP BY year
ORDER BY year;
"""
pd.read_sql(query_years, conn)

    year  count  avg_popularity
0   2000   3723       10.894977
1   2001   3562       11.530882
2   2002   3606       11.462840
3   2003   3708       12.231931
4   2004   3699       12.509057
5   2005   3657       13.996445
6   2006   3872       13.354855
7   2007   3992       13.722194
8   2008   4211       12.999763
9   2009   4131       14.850399
10  2010   4078       15.003923
11  2011   3887       16.107538
12  2012   4681       16.525101
13  2013   4515       17.451163
14  2014   4635       18.862352
15  2015   4585       20.234460
16  2016   3372       22.209964
17  2017   4752       23.332702
18  2018   4958       24.545785
19  2019   4886       26.188293
20  2020   4847       26.247163
21  2021   4532       28.270300
22  2022   4781       31.164401
23  2023   3330       19.683183

In [9]:
query_summary = """
SELECT
    MIN(popularity) AS min_pop,
    MAX(popularity) AS max_pop,
    AVG(popularity) AS avg_pop
FROM tracks;
"""
pd.read_sql(query_summary, conn)

   min_pop  max_pop  avg_pop
0        0       93  18.5381